steps:
- name: 'node:3.8.0'  
  entrypoint: npm  
  args: ['install']  
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args: ['app', 'deploy']  
